Revert "fix(TBD-10845): NoClassDefFoundError: org/apache/xbean/asm6/ClassVisitor for emr 5.29 (#1480)"
This reverts commit 95bf3653ca930dd4aa889632e15ff4d3e2218db3.