fix(TBD-9208): NoClassDefFoundError on spark batch job with ElasticSearch components
a missing jar was creating an error when using elasticsearch with CDH 6.1.1
fixed the template for Dynamic CDH6.1.1
generated the new built-in file